### ISSUE TITLE
Admin: Taxonomy order is not working.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Snuza#19]
Applicable to FAQ and Product category
Note: Page has been reloaded many times.
![image](https://cloud.githubusercontent.com/assets/11186313/11178417/b19b4252-8c87-11e5-9110-3048be50ca7c.png)

**Comment by jonathanza** [comment]
Sidebar is a custom menu. Order is not controlled via Taxonomy order. Not a bug.
