### ISSUE TITLE
Banner section: Clipped banner description for other if using other languages.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Snuza#3]
![image](https://cloud.githubusercontent.com/assets/11186313/11139272/46cb9782-8a08-11e5-8bd6-a0459b1de894.png)

**Comment by jonathanza** [comment]
This is not something we will fix. Client added this translation widget requirement after the project was at an advanced stage.

**Comment by roseliesromeo** [comment]
I can see this fixed in stage.
