### ISSUE TITLE
Newsletter: Section moves up and down as the testimonials auto rotate. It would be annoying for users when they try to key in their email address then the form moves down and the auto suggest blocks the field.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Snuza#8]
![image](https://cloud.githubusercontent.com/assets/11186313/11140335/5ce5e2aa-8a14-11e5-94d8-5e1052567c53.png)

**Comment by Sntax** [comment]
We have agreed to disable the auto rotate on testimonials to not only get around this issue but also allow the user to read the content at their own pace. The amount of text is widely different from testimonial to testimonial so applying a standardized "auto-time" to the testimonials results in a broken user experience. Fixed.
